GestionChambre/Models/Chambre.cs
namespace GestionChambre.Models
{
    public class Chambre
    {
        public  int Numero { get; set; }
        public string Type { get; set; } = "chambre simple,double,suite";
        public int Numero_etage { get; set; }
        public DateTime Date_Debut { get; set; }
        public DateTime Date_Fin {  get; set; }

    }
}

GestionChambre/Models/ErrorViewModel.cs
namespace GestionChambre.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GestionChambre/Controllers/ChambreController.cs
using GestionChambre.Data;
using GestionChambre.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace GestionChambre.Controllers
{
    public class ChambreController : Controller
    {
     
        private static List<Chambre> chambres = ChambreRepo.GetChambres();
        private static int Id = 6;
       
        public IActionResult Index()
        {
            ViewBag.chambres=chambres;
            return View();
        }


        [HttpGet]
        public IActionResult Ajouter() {
            Chambre chambre = new Chambre();
            chambre.Numero=Id++;
           
            return View(chambre);
        }


        [HttpPost]
        
        public IActionResult Ajouter(Chambre chambre)
        {
            chambres.Add(chambre);
            
            

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Modifier(int id)
        {
            Chambre chambre = chambres.Find(ck => ck.Numero == id);

            return View(chambre);
        }
        [HttpPost]
        public IActionResult Modifier(Chambre chambre)
        {
            Chambre c = chambres.Find(cb => cb.Numero == chambre.Numero);
            c.Type = chambre.Type;
            c.Numero_etage = chambre.Numero_etage;
            c.Date_Debut = chambre.Date_Debut;
            c.Date_Fin = chambre.Date_Fin;
           
            return RedirectToAction("Index");
        }

        public IActionResult Supprimer(int id)
        {
            Chambre chambre = chambres.Find(cb => cb.Numero == id);
            chambres.Remove(chambre);
            return RedirectToAction("Index");
        }

        public IActionResult ChambresDeuxiemeEtage()
        {
            ViewBag.chde = chambres.FindAll(ch => ch.Numero_etage == 2);
            return View();
        }

    }
}

GestionChambre/Controllers/HomeController.cs
using GestionChambre.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GestionChambre.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GestionChambre/Views/Chambre/Ajouter.cshtml
@model GestionChambre.Models.Chambre

@{
    ViewData["Title"] = "Chambre - Ajouter";
}


<h1>Chambre - Ajouter</h1>


<form method="post" asp-action="Ajouter">
    <fieldset>
        <legend>Chambre Informations</legend>
        <div class="form-group row">
            <label for="Isbn" class="col-sm-2 col-form-label">Numero</label>
            <div class="col-sm-10">
                <input asp-for="Numero" readonly class="form-control">
            </div>
        </div>

        <div class="form-group row">
            <label for="Titre" class="col-sm-2 col-form-label">Type</label>
            <div class="col-sm-10">
                <input asp-for="Type" class="form-control">
            </div>
        </div>

        <div class="form-group row">
            <label for="Auteur" class="col-sm-2 col-form-label">Numero Etage</label>
            <div class="col-sm-10">
                <input asp-for="Numero_etage" class="form-control">
            </div>
        </div>

        <div class="form-group row">
            <label for="DateEdition" class="col-sm-2 col-form-label">Date Debut</label>
            <div class="col-sm-10">
                <input asp-for="Date_Debut" class="form-control">
            </div>
        </div>

        <div class="form-group row">
            <label for="Resume" class="col-sm-2 col-form-label">Date Fin</label>
            <div class="col-sm-10">
                <input asp-for="Date_Fin" class="form-control">
            </div>
        </div>


        <button type="submit" class="btn btn-primary">Submit</button>
    </fieldset>
</form>

GestionChambre/Views/Chambre/ChambresDeuxiemeEtage.cshtml
@model List<Chambre>
    <h2>Chambres du 2ème étage</h2>

<h1>Liste des Chambres</h1>

@foreach (Chambre c in ViewBag.chde)
{
    <p>- Numero: @c.Numero</p>
    <p>- Type: @c.Type</p>
    <p>- Etage: @c.Numero_etage</p>
    <p>- Dates: @c.Date_Debut / @c.Date_Fin</p>
    <a asp-controller="Chambres" asp-action="Modifier" asp-route-num="@c.Numero">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z" />
        </svg>
    </a>
    <br />
    <a asp-controller="Chambres" asp-action="Supprimer" asp-route-num="@c.Numero">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5" />
        </svg>
    </a>
    <p>------------</p>
    <p>------------</p>
    <br />
}

GestionChambre/Views/Chambre/Index.cshtml
@model GestionChambre.Models.Chambre


@{
    ViewData["Title"] = "Chambre - Index";
}

<h1>Chambre - Index</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Numero</th>
            <th scope="col">Type</th>
            <th scope="col">Numero Etage</th>
            <th scope="col">Date Debut</th>
            <th scope="col">Date Fin</th>
            <th colspan="1" scope="col">Modifier</th>
            <th colspan="1" scope="col">Supprimer</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Chambre chambre in ViewBag.chambres)
        {
            <tr class="table-primary">
                <th scope="row">@chambre.Numero</th>
                <td>@chambre.Type</td>
                <td>@chambre.Numero_etage</td>
                <td>@chambre.Date_Debut</td>
                <td>@chambre.Date_Fin</td>
                <td>
                    <a asp-action="Modifier" asp-route-id="@chambre.Numero">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z" />
                        </svg>
                    </a>

                </td>

                <td>
                    <a asp-action="Supprimer" asp-route-id="@chambre.Numero">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5" />
                        </svg>
                    </a>
                </td>

            </tr>

        }




</table>

GestionChambre/Views/Chambre/Modifier.cshtml
@model GestionChambre.Models.Chambre

@{
    ViewData["Title"] = "Chambre - Modifier";
}

<h1>Chambre - Modifier</h1>

<form method="post" asp-action="Modifier">
    <fieldset>
        <legend>Modification Chambre</legend>
        <div class="form-group row">
            <label for="Numero" class="col-sm-2 col-form-label">Numero</label>
            <div class="col-sm-10">
                <input asp-for="Numero" readonly class="form-control">
            </div>
        </div>

        <div class="form-group row">
            <label for="Type" class="col-sm-2 col-form-label">Type</label>
            <div class="col-sm-10">
                <input asp-for="Type" class="form-control">
            </div>
        </div>

        <div class="form-group row">
            <label for="Numero_etage" class="col-sm-2 col-form-label">Numero Etage</label>
            <div class="col-sm-10">
                <input asp-for="Numero_etage" class="form-control">
            </div>
        </div>

        <div class="form-group row">
            <label for="Date_Debut" class="col-sm-2 col-form-label">Date Debut</label>
            <div class="col-sm-10">
                <input asp-for="Date_Debut" class="form-control">
            </div>
        </div>

        <div class="form-group row">
            <label for="Date_Fin" class="col-sm-2 col-form-label">Date Fin</label>
            <div class="col-sm-10">
                <input asp-for="Date_Fin" class="form-control">
            </div>
        </div>


        <button type="submit" class="btn btn-primary">Modifier</button>
    </fieldset>
</form>

GestionChambre/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GestionChambre/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestionChambre</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GestionChambre.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Chambre" asp-action="Index"><img src="../wwwroot/logo.jpg" height="50px" width="50px"/></a>
                <button class="navbar-toggler text-light active" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-light active" asp-area="" asp-controller="Chambre" asp-action="Index">List Chambres</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light active" asp-area="" asp-controller="Chambre" asp-action="Ajouter">Ajouter Chambres</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light active" asp-area="" asp-controller="Chambre" asp-action="ChambresDeuxiemeEtage">ChambresDeuxiemeEtage</a>
                        </li>

                        
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GestionChambre - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>